### ISSUE TITLE
ngAnnotate / Browserfy

### ISSUE THREAD

**Issue by LeviRosol** [trwolfe13/brewdown#2]
When using this in a project that uses ngAnnotate and browserfy, I get errors due to the ES6 syntax. Any chance you'd consider reworking things a bit so it can be used like other markdown-it plugins?

**Comment by trwolfe13** [comment]
Sure thing. I'll look at adding Babel into the build to get it transpiled to ES5.

**Comment by LeviRosol** [comment]
👍

**Comment by trwolfe13** [comment]
Version 1.2.0 (published in npm) should fix this issue. Let me know if you have any other trouble!

**Comment by LeviRosol** [comment]
Right on. I'll give it a shot in the next couple days.

I'm not sure I'll be using this though. A few weeks ago I started working on a project called [GM Binder](https://www.gmbinder.com) and due to some of the features in place / planned, adding new tags for stat blocks and what not may cause more work than it's worth.

honestly though, I'm torn. You've done good work here, and leveraging the power of parsing in markdown-it could be really useful like you've shown.

**Comment by trwolfe13** [comment]
I completely understand! GM Binder is a much more full-featured product. The brewdown library is really at its most use if you do what I do and keep my campaign notes in a private Git repository.
